#Set as appropriate on your instance. Left blank will disable the px-api connector
pxApi.baseUrls: #[
          #'http://beta-data.ssb.no/api/v0/no/table/',
          #'http://data.ssb.no/api/v0/no/table/'
          #]

logging:
  file: data-service.log
  level:
    'no.ssb': debug
    'org.springframework.web.client': debug